// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wmrsgtpspwkxvdgkkbgj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndtcnNndHBzcHdreHZkZ2trYmdqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDIzODQ0NTEsImV4cCI6MjA1Nzk2MDQ1MX0.JK01k0hw_pkjTHaq3rxySy7pFYIsPZpqgiWQy7JROBM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);